-- INSERTS for categories table

INSERT INTO categories (name, parent_id) VALUES ('Информационные технологии', NULL);
INSERT INTO categories (name, parent_id) VALUES ('Backend разработка', (SELECT id FROM categories WHERE name = 'Информационные технологии' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Frontend разработка', (SELECT id FROM categories WHERE name = 'Информационные технологии' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('QA', (SELECT id FROM categories WHERE name = 'Информационные технологии' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('DevOps', (SELECT id FROM categories WHERE name = 'Информационные технологии' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Data Science', (SELECT id FROM categories WHERE name = 'Информационные технологии' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('UI/UX дизайн', (SELECT id FROM categories WHERE name = 'Информационные технологии' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Строительство', NULL);
INSERT INTO categories (name, parent_id) VALUES ('Архитектор', (SELECT id FROM categories WHERE name = 'Строительство' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Инженер ПТО', (SELECT id FROM categories WHERE name = 'Строительство' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Прораб', (SELECT id FROM categories WHERE name = 'Строительство' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Сметчик', (SELECT id FROM categories WHERE name = 'Строительство' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Геодезист', (SELECT id FROM categories WHERE name = 'Строительство' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Здравоохранение', NULL);
INSERT INTO categories (name, parent_id) VALUES ('Врач-терапевт', (SELECT id FROM categories WHERE name = 'Здравоохранение' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Хирург', (SELECT id FROM categories WHERE name = 'Здравоохранение' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Медсестра', (SELECT id FROM categories WHERE name = 'Здравоохранение' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Фармацевт', (SELECT id FROM categories WHERE name = 'Здравоохранение' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Лаборант', (SELECT id FROM categories WHERE name = 'Здравоохранение' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Образование', NULL);
INSERT INTO categories (name, parent_id) VALUES ('Учитель начальных классов', (SELECT id FROM categories WHERE name = 'Образование' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Учитель математики', (SELECT id FROM categories WHERE name = 'Образование' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Учитель физики', (SELECT id FROM categories WHERE name = 'Образование' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Преподаватель ВУЗа', (SELECT id FROM categories WHERE name = 'Образование' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Методист', (SELECT id FROM categories WHERE name = 'Образование' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Финансы', NULL);
INSERT INTO categories (name, parent_id) VALUES ('Бухгалтер', (SELECT id FROM categories WHERE name = 'Финансы' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Аудитор', (SELECT id FROM categories WHERE name = 'Финансы' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Финансовый аналитик', (SELECT id FROM categories WHERE name = 'Финансы' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Экономист', (SELECT id FROM categories WHERE name = 'Финансы' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Кредитный специалист', (SELECT id FROM categories WHERE name = 'Финансы' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Маркетинг и реклама', NULL);
INSERT INTO categories (name, parent_id) VALUES ('Маркетолог', (SELECT id FROM categories WHERE name = 'Маркетинг и реклама' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('SMM-менеджер', (SELECT id FROM categories WHERE name = 'Маркетинг и реклама' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('PR-специалист', (SELECT id FROM categories WHERE name = 'Маркетинг и реклама' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Копирайтер', (SELECT id FROM categories WHERE name = 'Маркетинг и реклама' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Дизайнер рекламы', (SELECT id FROM categories WHERE name = 'Маркетинг и реклама' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Логистика и транспорт', NULL);
INSERT INTO categories (name, parent_id) VALUES ('Водитель', (SELECT id FROM categories WHERE name = 'Логистика и транспорт' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Экспедитор', (SELECT id FROM categories WHERE name = 'Логистика и транспорт' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Логист', (SELECT id FROM categories WHERE name = 'Логистика и транспорт' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Кладовщик', (SELECT id FROM categories WHERE name = 'Логистика и транспорт' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Диспетчер', (SELECT id FROM categories WHERE name = 'Логистика и транспорт' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Производство', NULL);
INSERT INTO categories (name, parent_id) VALUES ('Слесарь', (SELECT id FROM categories WHERE name = 'Производство' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Токарь', (SELECT id FROM categories WHERE name = 'Производство' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Электрик', (SELECT id FROM categories WHERE name = 'Производство' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Механик', (SELECT id FROM categories WHERE name = 'Производство' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Оператор станков', (SELECT id FROM categories WHERE name = 'Производство' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Юриспруденция', NULL);
INSERT INTO categories (name, parent_id) VALUES ('Юрист', (SELECT id FROM categories WHERE name = 'Юриспруденция' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Адвокат', (SELECT id FROM categories WHERE name = 'Юриспруденция' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Нотариус', (SELECT id FROM categories WHERE name = 'Юриспруденция' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Секретарь суда', (SELECT id FROM categories WHERE name = 'Юриспруденция' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Юрисконсульт', (SELECT id FROM categories WHERE name = 'Юриспруденция' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Сфера услуг', NULL);
INSERT INTO categories (name, parent_id) VALUES ('Парикмахер', (SELECT id FROM categories WHERE name = 'Сфера услуг' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Официант', (SELECT id FROM categories WHERE name = 'Сфера услуг' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Бармен', (SELECT id FROM categories WHERE name = 'Сфера услуг' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Администратор гостиницы', (SELECT id FROM categories WHERE name = 'Сфера услуг' LIMIT 1));
INSERT INTO categories (name, parent_id) VALUES ('Ресепшионист', (SELECT id FROM categories WHERE name = 'Сфера услуг' LIMIT 1));
